CREATE TABLE `Lines`(
lineId INT AUTO_INCREMENT,
startAt FLOAT NOT NULL,
remain FLOAT NOT NULL,
lyricsId INT NOT NULL,
PRIMARY KEY (lineId),
FOREIGN KEY (lyricsId) REFERENCES Lyrics (lyricsId)
ON DELETE CASCADE
);